#!/usr/bin/env bash
#
# Report what the build machine offers for signing, and write the same report to
# build/diagnostics/signing-environment.txt so it survives as a CI artifact.
#
# This answers one question: can the Apple Distribution certificate Codemagic
# injects be used by Apple's `shortcuts` CLI? Those are two different signing
# systems — app code signing uses certificates, private keys and provisioning
# profiles, while shortcut signing may use something else entirely — so the
# report gathers evidence for both and draws no conclusion on its own.
#
# Deliberately never fails: every probe is best-effort, because a missing tool
# is itself a finding. build_and_sign.sh is what fails the build.
#
# Nothing here prints a private key, password, token or account credential.
# `security find-identity` lists identity names and certificate hashes only;
# private keys stay in the keychain and are never exported.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DIAG_DIR="$REPO_ROOT/build/diagnostics"
REPORT="$DIAG_DIR/signing-environment.txt"

mkdir -p "$DIAG_DIR"

# Everything below is duplicated to the build log and the artifact.
exec > >(tee "$REPORT") 2>&1

section() {
    echo ""
    echo "=============================================================="
    echo "== $*"
    echo "=============================================================="
}

# Show the command before running it. Clearer than `set -x`, which would also
# trace the plumbing in this script and interleave badly with tee.
run() {
    echo "\$ $*"
    "$@" 2>&1 || echo "  [command failed or is unavailable: exit $?]"
    echo ""
}

echo "Signing environment report"
echo "Generated by scripts/diagnose_signing_env.sh"

section "Machine"
run sw_vers
run whoami
run uname -m

section "Shortcuts CLI presence"
if command -v shortcuts >/dev/null 2>&1; then
    echo "shortcuts found at: $(command -v shortcuts)"
else
    echo "shortcuts NOT FOUND on PATH — this machine cannot sign shortcuts at all."
fi
echo ""

section "Shortcuts CLI capabilities"
# Both spellings are tried because the subcommand help form differs by version.
run shortcuts help
run shortcuts help sign
run shortcuts sign --help

section "Does 'shortcuts sign' accept a certificate or identity?"
# Evidence for CASE C: if the CLI can be pointed at an installed certificate,
# the flag has to appear in its own help text. No flag is invented here.
if ! command -v shortcuts >/dev/null 2>&1; then
    echo "INCONCLUSIVE: the CLI is not installed, so its options cannot be read."
else
    # Only the CLI's own stdout counts. Capturing stderr here would let a
    # 'command not found' message masquerade as help text and produce a
    # confident verdict about a CLI that never ran.
    SIGN_HELP="$( { shortcuts help sign; shortcuts sign --help; } 2>/dev/null || true)"
    if [[ -z "${SIGN_HELP//[[:space:]]/}" ]]; then
        echo "INCONCLUSIVE: the CLI returned no help text for 'sign'."
    else
        MATCHES="$(printf '%s\n' "$SIGN_HELP" \
            | grep -iE -- '--(identity|certificate|cert|team|keychain|signing-identity)|\bidentity\b|\bcertificate\b|\bteam id\b' \
            || true)"
        if [[ -n "$MATCHES" ]]; then
            echo "POSSIBLE certificate/identity option found in help text:"
            printf '%s\n' "$MATCHES"
            echo ""
            echo "Investigate before concluding anything: a word match is not proof"
            echo "the option selects a keychain identity."
        else
            echo "NO certificate, identity, team or keychain option appears in the help"
            echo "text of the installed 'shortcuts sign'. On this evidence the CLI"
            echo "offers no way to point it at the injected Apple certificate."
            echo "The full help text is printed above; read it rather than trusting"
            echo "this grep alone."
        fi
    fi
fi
echo ""

section "Code signing identities (certificate + private key pairs)"
# An entry here means BOTH the certificate and its private key are present.
# This is the direct test of whether Codemagic's ios_signing injection worked.
if command -v security >/dev/null 2>&1; then
    run security find-identity -v -p codesigning
    echo "--- all identities, including any not valid for code signing ---"
    run security find-identity -p codesigning
else
    echo "'security' not available (not macOS)."
fi

section "Keychains on the search path"
if command -v security >/dev/null 2>&1; then
    run security list-keychains
    run security default-keychain
else
    echo "'security' not available (not macOS)."
fi

section "Apple certificates in the keychain (labels only)"
# Only labels and SHA-1 hashes — no PEM bodies, no keys. Dumping every
# certificate would bury the signal under the system trust store.
if command -v security >/dev/null 2>&1; then
    for label in "Apple Distribution" "Apple Development" "iPhone Distribution" "Developer ID Application"; do
        echo "\$ security find-certificate -a -c \"$label\" -Z | grep 'alis\\|SHA-1'"
        security find-certificate -a -c "$label" -Z 2>/dev/null \
            | grep -E '"alis"|SHA-1 hash' \
            || echo "  (none found)"
        echo ""
    done
else
    echo "'security' not available (not macOS)."
fi

section "iCloud account state"
# Count only. The account identifier itself is not printed.
if [[ "$(uname)" == "Darwin" ]]; then
    ACCOUNT_COUNT="$(defaults read MobileMeAccounts Accounts 2>/dev/null | grep -c 'AccountID' || true)"
    echo "iCloud accounts configured for this user: ${ACCOUNT_COUNT:-0}"
    if [[ "${ACCOUNT_COUNT:-0}" == "0" ]]; then
        echo "No iCloud account is signed in on this runner."
    fi
else
    echo "Not macOS — no iCloud state to read."
fi

echo ""
echo "=============================================================="
echo "== End of report"
echo "=============================================================="
